name = "StaticCondensation"
uuid = "d807e5ef-c177-4029-9a42-4f6bdd8c3f49"
authors = ["James Cook <cookjws@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
